# SITE CONFIGURATION
baseurl: ""
url: "https://inyourfacecomedy.ch"

# THEME-SPECIFIC CONFIGURATION
title: IN YOUR FACE Comedy                                    # site's title
description: "English Stand-Up Comedy in Zürich, Switzerland"      # used by search engines
avatar: assets/img/inyourface.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: English Stand-Up Comedy in Zürich  # Change Blog header text
header_feature_image: assets/img/header/inyourface.jpeg
header_feature_image_responsive: true
footer_text: >
  Get early updates on shows on the <a href="https://t.me/inyourfacecomedy">IN YOUR FACE Telegram Channel</a>

# Blog
excerpt: false                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: false
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.
future: true

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: false                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_tagmanager: GTM-M7Z9D4Z
google_analytics: G-JZBDD4CQWV                          # Tracking ID, e.g. "UA-000000-01"
meta_pixel: 5349931195130820                            # Tracking ID for Facebook Meta Pixel
cookie_consent: false                                   # To respect the usage of cookies
color_theme: dark                                       # auto, dark or light

include:
  - 4428d17dabee4ceb92c215e99a3dec6e.txt

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  shows:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
