backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-login}}
    update: Update {{collection}} “{{slug}}” - {{author-login}}
    delete: Delete {{collection}} “{{slug}}” - {{author-login}}
    uploadMedia: Upload “{{path}}” - {{author-login}}
    deleteMedia: Delete “{{path}}” - {{author-login}}

publish_mode: simple
media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "shows"
    label: "Shows"
    folder: "_posts"
    editor:
      preview: true
    filter: {field: "editable", value: "true"}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    encoding: "ascii"
    clean_accents: true
    sanitize_replacement: "_"
    extension: "md"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Editable", name: "editable", widget: "hidden", default: "true"}
      - { label: "Title", name: "title", widget: "string", hint: "Title of the show. Avoid quotes." }
      - { label: "Description", name: "description", widget: "string", hint: "Short 150 chars description for SEO"}
      - { label: "Feature Image", name: "feature-img", widget: "image", allow_multiple: false, hint: "Main image appears top of page as background. Recommend 1920x1005. Keep it under 300k for faster loading."}
      - { label: "Thumbnail", name: "thumbnail", widget: "image", allow_multiple: false, hint: "Square image e.g. 1080x1080. Keep it under 300k for faster loading. This is shown when sharing the link on e.g. WhatsApp"}
      - { label: "Author", name: "author", widget: "hidden", default: "harryfucks"}
      - { label: "Excerpt Separator", name: "excerpt_separator", widget: "hidden", default: "<!--more-->"}
      - { label: "Permalink", name: "permalink", widget: "string", hint: "Should begin and end in forward slack e.g. /comedybrew/", required: true}
      - { label: "Ticket URL", name: "ticket_url", widget: "string", hint: "Link to the ticket page for a nice red button. Use bit.ly to track!!!", required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', mode: 'rich_text', buttons: ['bold', 'italic', 'link', 'heading-one', 'heading-two', 'heading-three', 'bulleted-list', 'numbered-list'], 'editor_components': ['image'] }


